services:
  db:
    image: postgres:15.3
    container_name: postgres_db
    restart: always
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: migrations_studs
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - springboot-network

  app:
    image: docker-spring-boot-postgres:latest
    container_name: spring_app
    build: .
    working_dir: /app
    command: mvn spring-boot:run
    environment:
      TZ: America/Sao_Paulo
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/migrations_studs
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - springboot-network

networks:
  springboot-network:
    driver: bridge

volumes:
  postgres_data:
